#! python

def build(ctx):
    ctx(
        features='run_py_script',
        source='data_cleaning.py',
        deps=[
            ctx.path_to(ctx, 'IN_DATA', 'train.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'store.csv'),
            ctx.path_to(ctx, 'IN_DATA', 'test.csv')
        ],
        target=[
            ctx.path_to(ctx, 'OUT_FIGURES', 'train_store_coorr.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'monthly_sales.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'storetype_assortment_sales.pdf'),
            ctx.path_to(ctx, 'OUT_FIGURES', 'dayofweeksales.pdf'),
            ctx.path_to(ctx, 'OUT_DATA', 'clean_X.csv'),
            ctx.path_to(ctx, 'OUT_DATA', 'clean_y.csv'),
            ctx.path_to(ctx, 'OUT_DATA', 'clean_X_test.csv')
        ],
    )