#! python

def build(ctx):


    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='prediction.py',
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'clean_X.csv'),
            ctx.path_to(ctx, 'OUT_DATA', 'clean_y.csv'),
            ctx.path_to(ctx, 'OUT_DATA', 'clean_X_test.csv'),
            ctx.path_to(ctx, 'OUT_DATA', 'test.csv')
        ],
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'prediction_result.csv')
        ],
    )
